# Generated by Django 3.1.5 on 2021-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstpage', '0006_auto_20210204_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(blank=True, max_length=1),
        ),
    ]
